### ISSUE TITLE
Not able to pull image

### ISSUE THREAD

**Issue by jetzlstorfer** [al-lac/random-number-generator#1]
I'm not able to pull the image.

```
docker pull ghcr.io/al-lac/random-number-generator:main
Error response from daemon: Head "https://ghcr.io/v2/al-lac/random-number-generator/manifests/main": unauthorized
```

Maybe it is not publicly available?

Can you please have a look at this @al-lac ? Thank you :)

**Comment by al-lac** [comment]
Thanks @jetzlstorfer for pointing this out, was really set to private 🙈 

Should work now.

Changed it, also will adapt the README.md with an updated `docker run` command.
